Dexter/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'admin/',admin.site.urls),
    url(r'^$',views.homepage),
    url(r'^music/',include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music_ns'

urlpatterns = [
    url(r'^$',views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$' ,views.DetailView.as_view(),name='detail'),

    #/music/album/add/
    url(r'^album/add/$', views.CreateAlbum.as_view(),name='addAlbum'),

    #/music/album/pk-value/
    url(r'^(?P<pk>[0-9]+)/$' ,views.UpdateAlbum.as_view,name='updateAlbum'),

    #/music/album/pk-value/delete/
    url(r'^(?P<pk>[0-9]+)/delete/$' ,views.DeleteAlbum.as_view,name='deleteAlbum'),
]

music/models.py
from django.db import models
from django.urls import reverse

class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music_ns:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' --by-- ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_fav= models.BooleanField(default=False)

    def __str__(self):
        return self.song_title + '.' + self.file_type

Dexter/views.py
from django.http import HttpResponse

def homepage(request):
    return HttpResponse('HomePage( add new things for git)....')

music/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from  django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404
from .models import Album
from django.views import View

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    # context_object_name = 'object_list' #this is the default name
    context_object_name = 'albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'
    context_object_name = 'albums'

class CreateAlbum(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class UpdateAlbum(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class DeleteAlbum(DeleteView):
    model = Album
    success_url = reverse_lazy('music_ns:index')

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add a new Album {% endblock %}
{% block albums_active %}active{% endblock %}

{% block myBlock1 %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleName %}Dexter Kool{% endblock %}</title>

    {% load staticfiles %}
    <link rel="icon" href="http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/headphone-icon.png">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link href ='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/css-js/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrpcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--Headers-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#siteNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music_ns:index' %}"> <span class="glyphicon glyphicon-headphones" aria-hidden="true"></span> &nbsp; Dexter </a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="siteNavBar">
            <ul class="nav navbar-nav ">
                <!-- Alnums -->
                <li class="">
                    <a href="{% url 'music_ns:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span> &nbsp; Albums
                    </a>
                </li>

                <!--Music-->
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span> &nbsp; Songs
                    </a>
                </li>
            </ul>
            <!--Search Bar-->
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="myQuerry" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <!--right section-->
            <ul class="nav navbar-nav navbar-right">
                <!--Add Album-->
                <li class="">
                    <a href="{% url 'music_ns:addAlbum'%}">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> &nbsp; Add Album
                    </a>
                </li>
                <!--Logout-->
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> &nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
    <!--Child block 1-->
    {% block myBlock1 %}
    {% endblock %}
    <!--End of Child block 1-->
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block titleName %} Album Details Page {% endblock %}

{% block myBlock1 %}
    <img src="{{albums.album_logo.url}}" style="width : 250px;">

    <h1>{{albums.album_title}}</h1>
    <h2>{{albums.artist}}</h2>

    {% for song in albums.song_set.all %}
        {{ song.song_title }}
        {% if song.is_fav %}
            <img src="http://icons.iconarchive.com/icons/tpdkdesign.net/refresh-cl/16/Symbols-Favourite-2-icon.png"/>
        {% endif %}
        <br>
    {% endfor %}
{% endblock %}

music/templates/music/detail_old.html
{% extends 'music/base.html' %}
{% block titleName %} Album Details {% endblock %}
{% block myBlock1 %}
<img src="{{albums.album_logo}}">

<h1>{{albums.album_title}}</h1>
<h2>{{albums.artist}}</h2>

<!--
{% if error_message %}
<p><stron>{{ error_message}}</stron></p>
{% endif %}

<form action="{% url 'music_ns:fav' albums.id %}" method="post">
    {% csrf_token %}
    {% for song in albums.song_set.all %}
    <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{song.id}}">
    <label for="song{{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_fav %}
        <img src="http://icons.iconarchive.com/icons/tpdkdesign.net/refresh-cl/16/Symbols-Favourite-2-icon.png" />
        {% endif %}
    </label>
    <br>
    {% endfor %}
    <input type="Submit" value="Favourite">
</form>
-->
{% for song in object_list.song_set.all %}
{{ song.song_title }}
</label>
<br>
{% endfor %}

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.error}}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag}}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block albums_active %}Active{% endblock %}

{% block myBlock1 %}
<div class="albums-container container-fluid">

    <!--Albums-->
    <div class="row">
        {% if albums %}
        {% for album in albums %}
        <div class="col-sm-4 col-lg-2">
            <div class="thumbnail">
                <a href="{% url 'music_ns:detail' album.id %}">
                    <img src="{{ album.album_logo.url }}" class="img-responsive">
                </a>
                <div class="caption">
                    <h2>{{ album.album_title }}</h2>
                    <h4>{{ album.artist }}</h4>

                    <!--View Details-->
                    <a href="{% url 'music_ns:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                    <!--Delete Album-->
                    <form action="{% url 'music_ns:deleteAlbum' album.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="album_id" value="{{ album.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>


                </div>
            </div>
        </div>
        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% endfor %}
        {% else %}
        <div class="col-sm-12">
            <br>
            <a href="{% url 'music_ns:addAlbum' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                </button>
            </a>
        </div>
        {% endif %}
    </div>


</div>
{% endblock %}

music/templates/music/index_extra.html
{% extends 'music/base.html' %}
{% block albums_active %}active{% endblock %}

{% block myBlock1 %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <!--<div class="col-sm-12">-->
        <!--<h3>{{ user.username }}'s Albums</h3>-->
        <!--</div>-->
        {% if albums %}
        {% for album in albums %}
        <div class="col-sm-4 col-lg-2">
            <div class="thumbnail">
                <a href="{% url 'music_ns:detail' album.id %}">
                    <img src="{{ album.album_logo.url }}" class="img-responsive">
                </a>
                <div class="caption">
                    <h2>{{ album.album_title }}</h2>
                    <h4>{{ album.artist }}</h4>

                    <!-- View Details -->
                    <a href="{% url 'music_ns:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                    <!-- Delete Album -->
                    <form action="{% url 'music_ns:deleteAlbum' album.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="album_id" value="{{ album.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>

                    <!-- Favorite Album -->
                    <!--<a href="{% url 'music_ns:favorite_album' album.id %}" class="btn btn-default btn-sm btn-favorite" role="button">-->
                    <!--<span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>-->
                    <!--</a>-->

                </div>
            </div>
        </div>
        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% endfor %}
        {% else %}
        <div class="col-sm-12">
            <br>
            <a href="{% url 'music_ns:addAlbum' %}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                </button>
            </a>
        </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    <!--{% if songs %}-->
    <!--<div class="row">-->
    <!--<div class="col-sm-12">-->
    <!--<h3>Songs</h3>-->
    <!--</div>-->
    <!--<div class="col-sm-12">-->
    <!--<div class="panel panel-default">-->
    <!--<div class="panel-body">-->
    <!--<table class="table">-->
    <!--<thead>-->
    <!--<tr>-->
    <!--<th>Song Title</th>-->
    <!--<th>Artist</th>-->
    <!--<th>Audio File</th>-->
    <!--<th>Album</th>-->
    <!--<th>Favorite</th>-->
    <!--</tr>-->
    <!--</thead>-->
    <!--<tbody>-->
    <!--{% for song in songs %}-->
    <!--<tr>-->
    <!--<td>{{ song.song_title }}</td>-->
    <!--<td>{{ song.album.artist }}</td>-->
    <!--<td>-->
    <!--<a target="_blank" href="{{ song.audio_file.url }}">-->
    <!--<button type="button" class="btn btn-success btn-xs">-->
    <!--<span class="glyphicon glyphicon-play"></span>&nbsp; Play-->
    <!--</button>-->
    <!--</a>-->
    <!--</td>-->
    <!--<td>-->
    <!--<a href="{% url 'music:detail' song.album.id %}">-->
    <!--<img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />-->
    <!--</a>-->
    <!--<a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>-->
    <!--</td>-->
    <!--<td>-->
    <!--<a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>-->
    <!--</td>-->
    <!--</tr>-->
    <!--{% endfor %}-->
    <!--</tbody>-->
    <!--</table>-->
    <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    <!--{% endif %}-->

</div>
{% endblock %}

music/templates/music/index_old.html
{% extends 'music/base.html' %}

{% block myBlock1 %}
<ul>
    {% for album in album_names %}
    <li><a href="{% url 'music_ns:detail' album.id %}">{{album.album_title}}</a></li>
    {% endfor %}
</ul>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %} Register {% endblock %}
{% block albums_active %}active{% endblock %}

{% block myBlock1 %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <h3>Create a new Account</h3>

                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}